from typing import Optional
from jinja2 import Template
import shutil
from html2image import Html2Image
from pathlib import Path

from ranked.ranked_service import MatchInfo, RankedService
import util
from config import config
from ffmpeg_service import ffmpeg_service
from logger import setup_logger

logger = setup_logger(__name__)


class CoverGenerator:
    def __init__(self):
        template_file_path = config.template_dir / "cover_for_ranked.html"
        with open(template_file_path, "r", encoding="utf8") as template_file:
            self._template = Template(template_file.read())

        self._hti: Optional[Html2Image] = None
        logger.info(f"CoverGenerator测试中...")
        try:
            self._check()
        except Exception as e:
            logger.warning(e.args[0])
            logger.warning("CoverGenerator测试失败，已为您关闭封面生成功能！")
        else:
            self._hti = Html2Image(output_path=str(config.ranked_video_dir),
                                   browser_executable=str(config.browser_executable),
                                   disable_logging=True)


    @staticmethod
    def _check():
        if shutil.which(config.browser_executable) is None:
            raise EnvironmentError("未找到chrome.exe，请确保已在config.json中配置正确！"
                                   "（https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F1250504%2Fchrome-win.zip?generation=1705968802991678&alt=media）")

        test_hti = Html2Image(output_path=str(config.base_dir),
                              browser_executable=str(config.browser_executable),
                              disable_logging=True)
        save_as = 'helloworld.jpg'
        (config.base_dir / save_as).unlink(missing_ok=True)
        html_content = """
        <html>
          <body style="background-color:white;">
            <h1>Hello, World!</h1>
            <p>This is a screenshot generated by Html2Image.</p>
          </body>
        </html>
        """
        ret = test_hti.screenshot(html_str=html_content, save_as=save_as)
        if not Path(ret[0]).exists():
            raise EnvironmentError("CoverGenerator生成图片失败！可能是你的chromium版本太新！请尝试使用旧版本！"
                                   "（https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F1250504%2Fchrome-win.zip?generation=1705968802991678&alt=media）")
        logger.info("CoverGenerator检查通过！")

    def generate(self, video_path: Path, match_info: MatchInfo) -> Path:
        bg_path = config.ranked_video_dir / f'BG match[{match_info.id_}].jpg'
        ranked_icon_path = config.template_dir / "image" / "ranked_icon.png"
        font_path = config.template_dir / "fonts" / "mc.ttf"
        ffmpeg_service.screenshot(video_path=video_path, ss=120, output_path=bg_path)
        if self._hti is None:
            logger.info(f"未启用封面生成功能，直接使用{bg_path}作为封面")
            return bg_path
        if len(match_info.players) != 2:
            logger.info(f"非1v1，直接使用{bg_path}作为封面")
            return bg_path

        html_content = self._template.render(
            font_path=font_path.as_posix(),
            bg_path=bg_path.as_posix(),
            left_player=match_info.get_my_info().model_dump(include={'nickname', 'uuid'}),
            right_player=match_info.get_opponent_info().model_dump(include={'nickname', 'uuid'}),
            ranked_icon=ranked_icon_path.as_posix(),
            match_id=match_info.id_,
            result_time=util.ts_to_str(match_info.result.time)
        )
        save_as = f'cover match[{match_info.id_}].jpg'
        html_path = config.ranked_video_dir / f'cover match[{match_info.id_}].html'
        with open(html_path, 'w', encoding="utf8") as html_file:
            html_file.write(html_content)
        logger.debug(f"封面html文件已生成至{html_path}")
        ret = self._hti.screenshot(html_str=html_content, save_as=save_as)
        logger.info(f"封面已生成至{ret[0]}")

        return Path(ret[0])


def main():
    ranked_service = RankedService()
    cover_generator = CoverGenerator()
    cover_generator.generate(video_path=Path(r"D:\OBS Videos\Replay 2025-12-19 19-07-58.mp4"),
                         match_info=ranked_service.get_recent_matches()[0])

if __name__ == "__main__":
    main()