from typing import Optional
from jinja2 import Template
import shutil
from html2image import Html2Image
from pathlib import Path

from rsg.paceman_service import WorldData, LiveRunData, Event, paceman_service
import util
from config import config
from ffmpeg_service import ffmpeg_service
from translator import translator
from rsg.rsg_pb import rsg_pb
from logger import setup_logger

logger = setup_logger(__name__)

class CoverGenerator:
    _FINISH_IMAGE_PATH = config.template_dir / "image" / "Dragon_Egg.webp"
    _END_IMAGE_PATH = config.template_dir / "image" / "End_Stone.webp"
    _STRONGHOLD_IMAGE_PATH = config.template_dir / "image" / "Mossy_Stone_Bricks.webp"
    _FIRST_PORTAL_IMAGE_PATH = config.template_dir / "image" / "Eye_of_Ender.webp"

    def __init__(self):
        template_file_path = config.template_dir / "cover_for_rsg.html"
        with open(template_file_path, "r", encoding="utf8") as template_file:
            self._template = Template(template_file.read())

        self._hti: Optional[Html2Image] = None
        logger.info(f"CoverGenerator测试中...")
        try:
            self._check()
        except Exception as e:
            logger.warning(e.args[0])
            logger.warning("CoverGenerator测试失败，已为您关闭封面生成功能！")
        else:
            self._hti = Html2Image(output_path=str(config.video_dir),
                                   browser_executable=config.browser_executable,
                                   disable_logging=True)

    @staticmethod
    def _check():
        if shutil.which(config.browser_executable) is None:
            raise EnvironmentError("未找到chrome.exe，请确保已在config.json中配置正确！"
                                   "（https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F1250504%2Fchrome-win.zip?generation=1705968802991678&alt=media）")

        test_hti = Html2Image(output_path=config.base_dir, browser_executable=config.browser_executable,
                                   disable_logging=True)
        save_as = 'helloworld.jpg'
        (config.base_dir / save_as).unlink(missing_ok=True)
        html_content = """
        <html>
          <body style="background-color:white;">
            <h1>Hello, World!</h1>
            <p>This is a screenshot generated by Html2Image.</p>
          </body>
        </html>
        """
        ret = test_hti.screenshot(html_str=html_content, save_as=save_as)
        if not Path(ret[0]).exists():
            raise EnvironmentError("CoverGenerator生成图片失败！可能是你的chromium版本太新！请尝试使用旧版本！"
                                   "（https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F1250504%2Fchrome-win.zip?generation=1705968802991678&alt=media）")

        logger.info("CoverGenerator检查通过！")

    def get_corner_image_src(self, live_run: LiveRunData):
        image_src_dict = {
            "rsg.credits": self._FINISH_IMAGE_PATH,
            "rsg.enter_end": self._END_IMAGE_PATH,
            "rsg.enter_stronghold": self._STRONGHOLD_IMAGE_PATH,
            "rsg.first_portal": self._FIRST_PORTAL_IMAGE_PATH
        }
        return image_src_dict.get(live_run.eventList[-1].eventId, self._FINISH_IMAGE_PATH)


    def generate_event_str_list(self, live_run: LiveRunData) -> list[str]:
        def get_event_str(event: Event):
            event_str = f"{util.ts_to_str(event.igt)[:5]}{translator.event_map[event.eventId]}"
            if rsg_pb.is_pb(event):
                event_str += " PB"
            return event_str

        # 在event_list中，有若干rsg中的时间节点，例如盲传，进末地等
        # 在制作封面时，需要从这些时间节点中选择其中的三个用作展示
        # 为了选出相对“更有价值”的时间节点信息，我简单设计了一个算法
        # 主要逻辑是根据当前节点是否是pb，当前节点是否符合投稿时间要求来决定先后次序
        # 除此之外还手动指定了这些时间节点的先后顺序，当两个时间节点同时满足或者不满足上述的条件时，手动指定的顺序发挥作用
        # 这里我想到了两种实现方式：①手动编写lambda函数，直接比较两个节点谁“更有价值”
        #                      ②加权计算
        # 第一种方法我总觉得太绕，这里就用第二种方法写了

        def calculate_event_priority_score(event: Event):
            inner_html_order = ["rsg.credits", "rsg.first_portal", "rsg.enter_nether", "rsg.enter_end",
                                "rsg.enter_stronghold", "rsg.second_portal", "rsg.enter_fortress", "rsg.enter_bastion"]
            inner_html_map = {element: i for i, element in enumerate(inner_html_order)}
            base_priority = inner_html_map[event.eventId]
            pb_penalty = 0 if rsg_pb.is_pb(event) else 100
            upload_penalty = 0 if event.is_valid_for_upload() else 100
            return base_priority + pb_penalty + upload_penalty

        event_list = sorted(live_run.eventList, key=calculate_event_priority_score)
        # 只选择 3 个 event 进行展示
        event_list = event_list[:3]
        # 按照时间升序排序
        event_list.sort(key=Event.get_igt)
        return list(map(get_event_str, event_list))


    def generate(self, live_run: LiveRunData, world_data: WorldData, video_path: Path) -> Path:
        bg_path = config.video_dir / f'BG world[{world_data.data.id}].jpg'
        font_path = config.template_dir / "fonts" / "JiangChengLvDongHei.ttf"
        corner_image_src = self.get_corner_image_src(live_run)
        # 进入末地和隔墙有眼使用的图片是方块的图片，尺寸更大，CSS样式略有不同
        is_bigger_image = corner_image_src == self._END_IMAGE_PATH or corner_image_src == self._STRONGHOLD_IMAGE_PATH
        event_str_list = self.generate_event_str_list(live_run)
        points = live_run.get_points()
        ffmpeg_service.screenshot(video_path=video_path, ss=120, output_path=bg_path)
        if self._hti is None:
            logger.info(f"未启用封面生成功能，直接使用{bg_path}作为封面")
            return bg_path

        html_content = self._template.render(
            font_path=font_path.as_posix(),
            bg_path=bg_path.as_posix(),
            world_data=world_data.model_dump(),
            is_bigger_image=is_bigger_image,
            event_str_list=event_str_list,
            corner_image_src=corner_image_src,
            points=points,
        )
        save_as = f'cover world[{world_data.data.id}].jpg'
        html_path = config.video_dir / f'cover world[{world_data.data.id}].html'
        with open(html_path, 'w', encoding="utf8") as html_file:
            html_file.write(html_content)
        logger.debug(f"封面html文件已生成至{html_path}")
        ret = self._hti.screenshot(html_str=html_content, save_as=save_as)
        logger.info(f"封面已生成至{ret[0]}")

        return Path(ret[0])


if __name__ == "__main__":
    cover_generator = CoverGenerator()
    live = paceman_service.get_live_runs()[-1]
    world_data = paceman_service.get_world(live.worldId)
    cover_generator.generate(video_path=Path(r"D:\OBS Videos\Source Record\2025-04-13 14-41-26.mp4"),live_run=live,world_data=world_data)
